name: game

on:
  push:
    branches:
      - master
jobs:
  fs:
     runs-on: ubuntu-20.04
     steps:
      - name: Checkout source Code
        uses: actions/checkout@v1
      - name: Install the dependancies
        run: npm ci
      - name: End message
        run: echo 'All done'
       
